package com.github.xmaiax.input;

import static org.lwjgl.glfw.GLFW.*;

public enum InputedKey {

  _SPACE("Space", GLFW_KEY_SPACE),
  _MINUS("-", GLFW_KEY_MINUS),
  _APOSTROPHE("'", GLFW_KEY_APOSTROPHE),
  _COMMA(",", GLFW_KEY_COMMA),
  _PERIOD(".", GLFW_KEY_PERIOD),
  _SEMICOLON(";", GLFW_KEY_SEMICOLON),
  _SLASH("/", GLFW_KEY_SLASH),
  _BACKSLASH("\\", GLFW_KEY_BACKSLASH),
  _EQUAL("=", GLFW_KEY_EQUAL),
  _LEFT_BRACKET("{", GLFW_KEY_LEFT_BRACKET),
  _RIGHT_BRACKET("}", GLFW_KEY_RIGHT_BRACKET),
  _GRAVE_ACCENT("`", GLFW_KEY_GRAVE_ACCENT),
  _0("0", GLFW_KEY_0),
  _1("1", GLFW_KEY_1),
  _2("2", GLFW_KEY_2),
  _3("3", GLFW_KEY_3),
  _4("4", GLFW_KEY_4),
  _5("5", GLFW_KEY_5),
  _6("6", GLFW_KEY_6),
  _7("7", GLFW_KEY_7),
  _8("8", GLFW_KEY_8),
  _9("9", GLFW_KEY_9),
  _A("A", GLFW_KEY_A),
  _B("B", GLFW_KEY_B),
  _C("C", GLFW_KEY_C),
  _D("D", GLFW_KEY_D),
  _E("E", GLFW_KEY_E),
  _F("F", GLFW_KEY_F),
  _G("G", GLFW_KEY_G),
  _H("H", GLFW_KEY_H),
  _I("I", GLFW_KEY_I),
  _J("J", GLFW_KEY_J),
  _K("K", GLFW_KEY_K),
  _L("L", GLFW_KEY_L),
  _M("M", GLFW_KEY_M),
  _N("N", GLFW_KEY_N),
  _O("O", GLFW_KEY_O),
  _P("P", GLFW_KEY_P),
  _Q("Q", GLFW_KEY_Q),
  _R("R", GLFW_KEY_R),
  _S("S", GLFW_KEY_S),
  _T("T", GLFW_KEY_T),
  _U("U", GLFW_KEY_U),
  _V("V", GLFW_KEY_V),
  _W("W", GLFW_KEY_W),
  _X("X", GLFW_KEY_X),
  _Y("Y", GLFW_KEY_Y),
  _Z("Z", GLFW_KEY_Z),
  _WORLD_1("World 1", GLFW_KEY_WORLD_1),
  _WORLD_2("World 2", GLFW_KEY_WORLD_2),
  _ESCAPE("Escape", GLFW_KEY_ESCAPE),
  _ENTER("Enter", GLFW_KEY_ENTER),
  _TAB("Tab", GLFW_KEY_TAB),
  _BACKSPACE("Backspace", GLFW_KEY_BACKSPACE),
  _CAPS_LOCK("Caps Lock", GLFW_KEY_CAPS_LOCK),
  _INSERT("Insert", GLFW_KEY_INSERT),
  _DELETE("Delete", GLFW_KEY_DELETE),
  _UP("Up", GLFW_KEY_UP),
  _LEFT("Left", GLFW_KEY_LEFT),
  _DOWN("Down", GLFW_KEY_DOWN),
  _RIGHT("Right", GLFW_KEY_RIGHT),
  _PAGE_UP("Page Up", GLFW_KEY_PAGE_UP),
  _PAGE_DOWN("Page Down", GLFW_KEY_PAGE_DOWN),
  _HOME("Home", GLFW_KEY_HOME),
  _END("End", GLFW_KEY_END),
  _F1("F1", GLFW_KEY_F1),
  _F2("F2", GLFW_KEY_F2),
  _F3("F3", GLFW_KEY_F3),
  _F4("F4", GLFW_KEY_F4),
  _F5("F5", GLFW_KEY_F5),
  _F6("F6", GLFW_KEY_F6),
  _F7("F7", GLFW_KEY_F7),
  _F8("F8", GLFW_KEY_F8),
  _F9("F9", GLFW_KEY_F9),
  _F10("F10", GLFW_KEY_F10),
  _F11("F11", GLFW_KEY_F11),
  _F12("F12", GLFW_KEY_F12),
  _F13("F13", GLFW_KEY_F13),
  _F14("F14", GLFW_KEY_F14),
  _F15("F15", GLFW_KEY_F15),
  _F16("F16", GLFW_KEY_F16),
  _F17("F17", GLFW_KEY_F17),
  _F18("F18", GLFW_KEY_F18),
  _F19("F19", GLFW_KEY_F19),
  _F20("F20", GLFW_KEY_F20),
  _F21("F21", GLFW_KEY_F21),
  _F22("F22", GLFW_KEY_F22),
  _F23("F23", GLFW_KEY_F23),
  _F24("F24", GLFW_KEY_F24),
  _F25("F25", GLFW_KEY_F25),
  _PRINT_SCREEN("Print Screen", GLFW_KEY_PRINT_SCREEN),
  _SCROLL_LOCK("Scroll Lock", GLFW_KEY_SCROLL_LOCK),
  _PAUSE("Pause", GLFW_KEY_PAUSE),
  _NUM_LOCK("Num Lock", GLFW_KEY_NUM_LOCK),
  _KP_0("[Num] 0", GLFW_KEY_KP_0),
  _KP_1("[Num] 1", GLFW_KEY_KP_1),
  _KP_2("[Num] 2", GLFW_KEY_KP_2),
  _KP_3("[Num] 3", GLFW_KEY_KP_3),
  _KP_4("[Num] 4", GLFW_KEY_KP_4),
  _KP_5("[Num] 5", GLFW_KEY_KP_5),
  _KP_6("[Num] 6", GLFW_KEY_KP_6),
  _KP_7("[Num] 7", GLFW_KEY_KP_7),
  _KP_8("[Num] 8", GLFW_KEY_KP_8),
  _KP_9("[Num] 9", GLFW_KEY_KP_9),
  _KP_ADD("[Num] +", GLFW_KEY_KP_ADD),
  _KP_SUBTRACT("[Num] -", GLFW_KEY_KP_SUBTRACT),
  _KP_MULTIPLY("[Num] *", GLFW_KEY_KP_MULTIPLY),
  _KP_DIVIDE("[Num] /", GLFW_KEY_KP_DIVIDE),
  _KP_ENTER("[Num] Enter", GLFW_KEY_KP_ENTER),
  _KP_EQUAL("[Num] =", GLFW_KEY_KP_EQUAL),
  _KP_COMMA("[Num] .", GLFW_KEY_KP_DECIMAL),
  _LEFT_SHIFT("Left Shift", GLFW_KEY_LEFT_SHIFT),
  _RIGHT_SHIFT("Right Shift", GLFW_KEY_RIGHT_SHIFT),
  _LEFT_CONTROL("Left Control", GLFW_KEY_LEFT_CONTROL),
  _RIGHT_CONTROL("Right Control", GLFW_KEY_RIGHT_CONTROL),
  _LEFT_ALT("Left Alt", GLFW_KEY_LEFT_ALT),
  _RIGHT_ALT("Right Alt", GLFW_KEY_RIGHT_ALT),
  _LEFT_SUPER("Left Super", GLFW_KEY_LEFT_SUPER),
  _RIGHT_SUPER("Right Super", GLFW_KEY_RIGHT_SUPER),
  _MENU("Menu", GLFW_KEY_MENU),
  _LAST("Last", GLFW_KEY_LAST),
  _GAMEPAD_L1("[Gamepad] L1", GLFW_GAMEPAD_BUTTON_LEFT_BUMPER),
  _GAMEPAD_R2("[Gamepad] R1", GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER),
  _GAMEPAD_SELECT("[Gamepad] Select", GLFW_GAMEPAD_BUTTON_BACK),
  _GAMEPAD_START("[Gamepad] Start", GLFW_GAMEPAD_BUTTON_START),
  _GAMEPAD_L3("[Gamepad] L3", GLFW_GAMEPAD_BUTTON_LEFT_THUMB),
  _GAMEPAD_R3("[Gamepad] R3", GLFW_GAMEPAD_BUTTON_RIGHT_THUMB),
  _GAMEPAD_DPAD_UP("[Gamepad] Digital Pad Up", GLFW_GAMEPAD_BUTTON_DPAD_UP),
  _GAMEPAD_DPAD_RIGHT("[Gamepad] Digital Pad Right", GLFW_GAMEPAD_BUTTON_DPAD_RIGHT),
  _GAMEPAD_DPAD_DOWN("[Gamepad] Digital Pad Down", GLFW_GAMEPAD_BUTTON_DPAD_DOWN),
  _GAMEPAD_DPAD_LEFT("[Gamepad] Digital Pad Left", GLFW_GAMEPAD_BUTTON_DPAD_LEFT),
  _GAMEPAD_CROSS("[Gamepad] Cross", GLFW_GAMEPAD_BUTTON_CROSS),
  _GAMEPAD_CIRCLE("[Gamepad] Circle", GLFW_GAMEPAD_BUTTON_CIRCLE),
  _GAMEPAD_SQUARE("[Gamepad] Square", GLFW_GAMEPAD_BUTTON_SQUARE),
  _GAMEPAD_TRIANGLE("[Gamepad] Triangle", GLFW_GAMEPAD_BUTTON_TRIANGLE),

  ;

  private final String alias;
  @Override public String toString() { return this.alias; }

  private final int glfwCode;
  public int getGlfwCode() { return this.glfwCode; }

  private InputedKey(final String alias, final int glfwCode) {
    this.alias = alias;
    this.glfwCode = glfwCode;
  }

  public static InputedKey fromCode(final int code) {
    return java.util.Arrays.asList(InputedKey.values()).stream()
      .filter(ik -> ik.getGlfwCode() == code)
        .findFirst().orElse(null);
  }

}
